name: Deploy Changed Docker Compose Stacks

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Filter Changed Files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            traefik:
              - 'docker-compose/traefik/**'
            nautobot:
              - 'docker-compose/nautobot/**'
            netbox:
              - 'docker-compose/netbox/**'
            netdisco:
              - 'docker-compose/netdisco/**'

  deploy:
    runs-on: self-hosted
    needs: detect-changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Traefik
        if: steps.changes.outputs.traefik == 'true'
        run: |
          cd docker-compose/traefik
          docker compose down
          docker compose up -d

      - name: Deploy Nautobot
        if: steps.changes.outputs.nautobot == 'true'
        run: |
          cd docker-compose/nautobot
          docker compose down
          docker compose up -d

      - name: Deploy Netbox
        if: steps.changes.outputs.netbox == 'true'
        run: |
          cd docker-compose/netbox
          docker compose down
          docker compose up -d

      - name: Deploy Netdisco
        if: steps.changes.outputs.netdisco == 'true'
        run: |
          cd docker-compose/netdisco
          docker compose down
          docker compose up -d
