services:
  netdisco-postgresql:
    image: netdisco/netdisco:latest-postgresql
    hostname: netdisco-postgresql
    container_name: netdisco-postgresql
    volumes:
      - "/opt/appdata/netdisco-postgresql/pgdata:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - plexguide

  netdisco-backend:
    image: netdisco/netdisco:latest-backend
    hostname: netdisco-backend
    container_name: netdisco-backend
    init: true
    volumes:
      - "/opt/appdata/netdisco-backend/nd-site-local:/home/netdisco/nd-site-local"
      - "/opt/appdata/netdisco-backend/config:/home/netdisco/environments"
      - "/opt/appdata/netdisco-backend/logs:/home/netdisco/logs"
    environment:
      NETDISCO_DOMAIN: discover
      NETDISCO_DB_HOST: netdisco-postgresql
    depends_on:
      - netdisco-postgresql
    dns_opt:
      - 'ndots:0'
      - 'timeout:1'
      - 'retries:0'
      - 'attempts:1'
      - edns0
      - trustad
    restart: unless-stopped
    networks:
      - plexguide

  netdisco-web:
    image: netdisco/netdisco:latest-web
    hostname: netdisco-web
    container_name: netdisco-web
    init: true
    volumes:
      - "/opt/appdata/netdisco-web/nd-site-local:/home/netdisco/nd-site-local"
      - "/opt/appdata/netdisco-web/config:/home/netdisco/environments"
    environment:
      NETDISCO_DOMAIN: discover
      NETDISCO_DB_HOST: netdisco-postgresql
      IPV: 4
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.oauth.forwardauth.address=http://oauth:4181
      - traefik.http.middlewares.netdisco.headers.sslHost=ibhacked.us
      - traefik.http.middlewares.netdisco.headers.sslRedirect=true
      - traefik.http.middlewares.netdisco.headers.stsIncludeSubdomains=true
      - traefik.http.routers.netdisco.entrypoints=https
      - traefik.http.routers.netdisco.middlewares=oauth
      - traefik.http.routers.netdisco.rule=Host(`netdisco.ibhacked.us`)
      - traefik.http.routers.netdisco.tls=true
      - traefik.http.services.netdisco.loadbalancer.server.port=5000
    depends_on:
      - netdisco-postgresql
    dns_opt:
      - 'ndots:0'
      - 'timeout:1'
      - 'retries:0'
      - 'attempts:1'
      - edns0
      - trustad
    restart: unless-stopped
    networks:
      - plexguide

  netdisco-do:
    image: netdisco/netdisco:latest-do
    hostname: netdisco-backend
    container_name: netdisco-do
    volumes:
      - "/opt/appdata/netdisco-do/nd-site-local:/home/netdisco/nd-site-local"
      - "/opt/appdata/netdisco-do/config:/home/netdisco/environments"
    environment:
      NETDISCO_DOMAIN: discover
      NETDISCO_DB_HOST: netdisco-postgresql
    depends_on:
      - netdisco-postgresql
    profiles:
      - cli-manual
    restart: unless-stopped
    networks:
      - plexguide

volumes:
  netdisco_pgdata:
    driver: local
  netdisco_logs:
    driver: local
  netdisco_config:
    driver: local
  netdisco_site_local:
    driver: local

networks:
  plexguide:
    external: true